// src/lib/mock-data.ts
export const mockData = {
  liveData: [
    {
      id: '000000123',
      name: 'KINDRED INOCENCIO',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000481',
      name: 'YMES INOCENCIO',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'remarks',
    },
    {
      id: '000000124',
      name: 'JOHN DOE',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000482',
      name: 'JANE SMITH',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'not-allowed',
    },
    {
      id: '000000125',
      name: 'ALICE JOHNSON',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000483',
      name: 'BOB BROWN',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'remarks',
    },
    {
      id: '000000126',
      name: 'CHARLIE BLACK',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'not-allowed',
    },
    {
      id: '000000484',
      name: 'DAVE WHITE',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'allowed',
    },
    {
      id: '000000127',
      name: 'EVE GREEN',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000485',
      name: 'FRANK GRAY',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'remarks',
    },
    {
      id: '000000128',
      name: 'GRACE BLUE',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000486',
      name: 'HELEN PURPLE',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'not-allowed',
    },
    {
      id: '000000129',
      name: 'IVAN ORANGE',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000487',
      name: 'JACK YELLOW',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'remarks',
    },
    {
      id: '000000130',
      name: 'KATE PINK',
      type: 'STUDENT',
      gate: 'GATE A',
      activity: 'IN',
      status: 'allowed',
    },
    {
      id: '000000488',
      name: 'LUCY CYAN',
      type: 'EMPLOYEE',
      gate: 'GATE B',
      activity: 'OUT',
      status: 'not-allowed',
    },
  ],
};
